
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'AllowancesOptionsCreate': typeof import("../components/AllowancesOptions/Create.vue")['default']
    'AllowancesOptionsList': typeof import("../components/AllowancesOptions/List.vue")['default']
    'AllowancesOptionsUpdate': typeof import("../components/AllowancesOptions/Update.vue")['default']
    'AvatarPicker': typeof import("../components/AvatarPicker.vue")['default']
    'BackendErrorWrapper': typeof import("../components/BackendErrorWrapper.vue")['default']
    'CreateEmployeeAuthentication': typeof import("../components/CreateEmployee/Authentication.vue")['default']
    'CreateEmployeeContactInfo': typeof import("../components/CreateEmployee/ContactInfo.vue")['default']
    'CreateEmployeeEmploymentInfo': typeof import("../components/CreateEmployee/EmploymentInfo.vue")['default']
    'CreateEmployeePersonalInfo': typeof import("../components/CreateEmployee/PersonalInfo.vue")['default']
    'CreateEmployeeSalary': typeof import("../components/CreateEmployee/Salary.vue")['default']
    'CreateEmployeeSalarySelectAllowances': typeof import("../components/CreateEmployee/SalarySelectAllowances.vue")['default']
    'CreateEmployeeSalarySelectDeductions': typeof import("../components/CreateEmployee/SalarySelectDeductions.vue")['default']
    'CreateEmployeeSelectRoles': typeof import("../components/CreateEmployee/SelectRoles.vue")['default']
    'CreateEmployeeSetPassword': typeof import("../components/CreateEmployee/SetPassword.vue")['default']
    'CreateMemberContactInfoOld': typeof import("../components/CreateMember/ContactInfo.old.vue")['default']
    'CreateMemberContactInfo': typeof import("../components/CreateMember/ContactInfo.vue")['default']
    'CreateMemberMembershipInfo': typeof import("../components/CreateMember/MembershipInfo.vue")['default']
    'CreateMemberPersonalInfoOld': typeof import("../components/CreateMember/PersonalInfo.old.vue")['default']
    'CreateMemberPersonalInfo': typeof import("../components/CreateMember/PersonalInfo.vue")['default']
    'CreateRoleSelectPermissions': typeof import("../components/CreateRole/SelectPermissions.vue")['default']
    'CreateUserAvatarPicker': typeof import("../components/CreateUser/AvatarPicker.vue")['default']
    'CreateUserSelectRoles': typeof import("../components/CreateUser/SelectRoles.vue")['default']
    'CreateUserDetails': typeof import("../components/CreateUser/UserDetails.vue")['default']
    'DatePicker': typeof import("../components/DatePicker.vue")['default']
    'DateView': typeof import("../components/DateView.vue")['default']
    'DeductionsOptionsCreate': typeof import("../components/DeductionsOptions/Create.vue")['default']
    'DeductionsOptionsList': typeof import("../components/DeductionsOptions/List.vue")['default']
    'DeductionsOptionsUpdate': typeof import("../components/DeductionsOptions/Update.vue")['default']
    'DefaultLayoutNavigationRail': typeof import("../components/DefaultLayout/NavigationRail.vue")['default']
    'DefaultLayoutUserCard': typeof import("../components/DefaultLayout/UserCard.vue")['default']
    'EmployeesEmployeeAuthInfo': typeof import("../components/Employees/EmployeeAuthInfo.vue")['default']
    'EmployeesEmployeeInfo': typeof import("../components/Employees/EmployeeInfo.vue")['default']
    'EmployeesEmployeeSalaryInfo': typeof import("../components/Employees/EmployeeSalaryInfo.vue")['default']
    'EmployeesEmployeeSettings': typeof import("../components/Employees/EmployeeSettings.vue")['default']
    'EmployeesList': typeof import("../components/Employees/List.vue")['default']
    'LoadingFromBackend': typeof import("../components/LoadingFromBackend.vue")['default']
    'MembersEmployeeSalaryInfo': typeof import("../components/Members/EmployeeSalaryInfo.vue")['default']
    'MembersList': typeof import("../components/Members/List.vue")['default']
    'MembersMemberInfo': typeof import("../components/Members/MemberInfo.vue")['default']
    'MembersMemberSettings': typeof import("../components/Members/MemberSettings.vue")['default']
    'MultiPhoneField': typeof import("../components/MultiPhoneField.vue")['default']
    'NumberField': typeof import("../components/NumberField.vue")['default']
    'PasswordField': typeof import("../components/PasswordField.vue")['default']
    'ProjectsActivityAddStaff': typeof import("../components/Projects/Activity/AddStaff.vue")['default']
    'ProjectsActivityFinance': typeof import("../components/Projects/Activity/Finance.vue")['default']
    'ProjectsActivityFinanceCreateFinance': typeof import("../components/Projects/Activity/Finance/CreateFinance.vue")['default']
    'ProjectsActivityFinanceDonations': typeof import("../components/Projects/Activity/Finance/Donations.vue")['default']
    'ProjectsActivityFinanceDonationsList': typeof import("../components/Projects/Activity/Finance/DonationsList.vue")['default']
    'ProjectsActivityFinanceExpenses': typeof import("../components/Projects/Activity/Finance/Expenses.vue")['default']
    'ProjectsActivityFinanceExpensesListOld': typeof import("../components/Projects/Activity/Finance/ExpensesList.old.vue")['default']
    'ProjectsActivityFinanceExpensesList': typeof import("../components/Projects/Activity/Finance/ExpensesList.vue")['default']
    'ProjectsActivityFinanceList': typeof import("../components/Projects/Activity/Finance/List.vue")['default']
    'ProjectsActivityFinanceUpdateFinance': typeof import("../components/Projects/Activity/Finance/UpdateFinance.vue")['default']
    'ProjectsActivitySetStaffData': typeof import("../components/Projects/Activity/SetStaffData.vue")['default']
    'ProjectsActivityStaff': typeof import("../components/Projects/Activity/Staff.vue")['default']
    'ProjectsActivityStaffCard': typeof import("../components/Projects/Activity/StaffCard.vue")['default']
    'ProjectsActivityStaffList': typeof import("../components/Projects/Activity/StaffList.vue")['default']
    'ProjectsActivityUpdateStaff': typeof import("../components/Projects/Activity/UpdateStaff.vue")['default']
    'ProjectsActivityViewData': typeof import("../components/Projects/Activity/ViewData.vue")['default']
    'ProjectsCreateData': typeof import("../components/Projects/CreateData.vue")['default']
    'ProjectsFinance': typeof import("../components/Projects/Finance.vue")['default']
    'ProjectsFinanceCreateProjectFinance': typeof import("../components/Projects/Finance/CreateProjectFinance.vue")['default']
    'ProjectsFinanceDonations': typeof import("../components/Projects/Finance/Donations.vue")['default']
    'ProjectsFinanceDonationsList': typeof import("../components/Projects/Finance/DonationsList.vue")['default']
    'ProjectsFinanceExpenses': typeof import("../components/Projects/Finance/Expenses.vue")['default']
    'ProjectsFinanceExpensesList': typeof import("../components/Projects/Finance/ExpensesList.vue")['default']
    'ProjectsFinanceUpdateProjectFinance': typeof import("../components/Projects/Finance/UpdateProjectFinance.vue")['default']
    'ProjectsList': typeof import("../components/Projects/List.vue")['default']
    'ProjectsProjectActivities': typeof import("../components/Projects/Project/Activities.vue")['default']
    'ProjectsProjectActivitySettings': typeof import("../components/Projects/Project/ActivitySettings.vue")['default']
    'ProjectsProjectAddStaff': typeof import("../components/Projects/Project/AddStaff.vue")['default']
    'ProjectsProjectCreateActivity': typeof import("../components/Projects/Project/CreateActivity.vue")['default']
    'ProjectsProjectSettings': typeof import("../components/Projects/Project/Settings.vue")['default']
    'ProjectsProjectStaffCard': typeof import("../components/Projects/Project/StaffCard.vue")['default']
    'ProjectsProjectStaffList': typeof import("../components/Projects/Project/StaffList.vue")['default']
    'ProjectsProjectUpdateActivity': typeof import("../components/Projects/Project/UpdateActivity.vue")['default']
    'ProjectsProjectUpdateStaff': typeof import("../components/Projects/Project/UpdateStaff.vue")['default']
    'ProjectsProjectViewData': typeof import("../components/Projects/Project/ViewData.vue")['default']
    'ProjectsSetStaffData': typeof import("../components/Projects/SetStaffData.vue")['default']
    'ProjectsStaff': typeof import("../components/Projects/Staff.vue")['default']
    'SaveCancelBtn': typeof import("../components/SaveCancelBtn.vue")['default']
    'SelectField': typeof import("../components/SelectField.vue")['default']
    'TextEditor': typeof import("../components/TextEditor.vue")['default']
    'TextField': typeof import("../components/TextField.vue")['default']
    'TextareaField': typeof import("../components/TextareaField.vue")['default']
    'WContactInfo': typeof import("../components/w/ContactInfo.vue")['default']
    'WHtmlView': typeof import("../components/w/HtmlView.vue")['default']
    'WHtmlViewDialog': typeof import("../components/w/HtmlViewDialog.vue")['default']
    'WIdInfo': typeof import("../components/w/IdInfo.vue")['default']
    'WMaritalStatusPicker': typeof import("../components/w/MaritalStatusPicker.vue")['default']
    'WSelectAllowances': typeof import("../components/w/SelectAllowances.vue")['default']
    'WSelectDeductions': typeof import("../components/w/SelectDeductions.vue")['default']
    'WSelectEmployee': typeof import("../components/w/SelectEmployee.vue")['default']
    'WSelectEmploymentStatus': typeof import("../components/w/SelectEmploymentStatus.vue")['default']
    'WSelectMember': typeof import("../components/w/SelectMember.vue")['default']
    'WSelectMembershipStatus': typeof import("../components/w/SelectMembershipStatus.vue")['default']
    'WSelectOrgSection': typeof import("../components/w/SelectOrgSection.vue")['default']
    'WSelectQualification': typeof import("../components/w/SelectQualification.vue")['default']
    'WSexPicker': typeof import("../components/w/SexPicker.vue")['default']
    'WUsd': typeof import("../components/w/Usd.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'TiptapEditorContent': typeof import("@tiptap/vue-3")['EditorContent']
    'TiptapFloatingMenu': typeof import("@tiptap/vue-3")['FloatingMenu']
    'TiptapBubbleMenu': typeof import("@tiptap/vue-3")['BubbleMenu']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyAllowancesOptionsCreate': typeof import("../components/AllowancesOptions/Create.vue")['default']
    'LazyAllowancesOptionsList': typeof import("../components/AllowancesOptions/List.vue")['default']
    'LazyAllowancesOptionsUpdate': typeof import("../components/AllowancesOptions/Update.vue")['default']
    'LazyAvatarPicker': typeof import("../components/AvatarPicker.vue")['default']
    'LazyBackendErrorWrapper': typeof import("../components/BackendErrorWrapper.vue")['default']
    'LazyCreateEmployeeAuthentication': typeof import("../components/CreateEmployee/Authentication.vue")['default']
    'LazyCreateEmployeeContactInfo': typeof import("../components/CreateEmployee/ContactInfo.vue")['default']
    'LazyCreateEmployeeEmploymentInfo': typeof import("../components/CreateEmployee/EmploymentInfo.vue")['default']
    'LazyCreateEmployeePersonalInfo': typeof import("../components/CreateEmployee/PersonalInfo.vue")['default']
    'LazyCreateEmployeeSalary': typeof import("../components/CreateEmployee/Salary.vue")['default']
    'LazyCreateEmployeeSalarySelectAllowances': typeof import("../components/CreateEmployee/SalarySelectAllowances.vue")['default']
    'LazyCreateEmployeeSalarySelectDeductions': typeof import("../components/CreateEmployee/SalarySelectDeductions.vue")['default']
    'LazyCreateEmployeeSelectRoles': typeof import("../components/CreateEmployee/SelectRoles.vue")['default']
    'LazyCreateEmployeeSetPassword': typeof import("../components/CreateEmployee/SetPassword.vue")['default']
    'LazyCreateMemberContactInfoOld': typeof import("../components/CreateMember/ContactInfo.old.vue")['default']
    'LazyCreateMemberContactInfo': typeof import("../components/CreateMember/ContactInfo.vue")['default']
    'LazyCreateMemberMembershipInfo': typeof import("../components/CreateMember/MembershipInfo.vue")['default']
    'LazyCreateMemberPersonalInfoOld': typeof import("../components/CreateMember/PersonalInfo.old.vue")['default']
    'LazyCreateMemberPersonalInfo': typeof import("../components/CreateMember/PersonalInfo.vue")['default']
    'LazyCreateRoleSelectPermissions': typeof import("../components/CreateRole/SelectPermissions.vue")['default']
    'LazyCreateUserAvatarPicker': typeof import("../components/CreateUser/AvatarPicker.vue")['default']
    'LazyCreateUserSelectRoles': typeof import("../components/CreateUser/SelectRoles.vue")['default']
    'LazyCreateUserDetails': typeof import("../components/CreateUser/UserDetails.vue")['default']
    'LazyDatePicker': typeof import("../components/DatePicker.vue")['default']
    'LazyDateView': typeof import("../components/DateView.vue")['default']
    'LazyDeductionsOptionsCreate': typeof import("../components/DeductionsOptions/Create.vue")['default']
    'LazyDeductionsOptionsList': typeof import("../components/DeductionsOptions/List.vue")['default']
    'LazyDeductionsOptionsUpdate': typeof import("../components/DeductionsOptions/Update.vue")['default']
    'LazyDefaultLayoutNavigationRail': typeof import("../components/DefaultLayout/NavigationRail.vue")['default']
    'LazyDefaultLayoutUserCard': typeof import("../components/DefaultLayout/UserCard.vue")['default']
    'LazyEmployeesEmployeeAuthInfo': typeof import("../components/Employees/EmployeeAuthInfo.vue")['default']
    'LazyEmployeesEmployeeInfo': typeof import("../components/Employees/EmployeeInfo.vue")['default']
    'LazyEmployeesEmployeeSalaryInfo': typeof import("../components/Employees/EmployeeSalaryInfo.vue")['default']
    'LazyEmployeesEmployeeSettings': typeof import("../components/Employees/EmployeeSettings.vue")['default']
    'LazyEmployeesList': typeof import("../components/Employees/List.vue")['default']
    'LazyLoadingFromBackend': typeof import("../components/LoadingFromBackend.vue")['default']
    'LazyMembersEmployeeSalaryInfo': typeof import("../components/Members/EmployeeSalaryInfo.vue")['default']
    'LazyMembersList': typeof import("../components/Members/List.vue")['default']
    'LazyMembersMemberInfo': typeof import("../components/Members/MemberInfo.vue")['default']
    'LazyMembersMemberSettings': typeof import("../components/Members/MemberSettings.vue")['default']
    'LazyMultiPhoneField': typeof import("../components/MultiPhoneField.vue")['default']
    'LazyNumberField': typeof import("../components/NumberField.vue")['default']
    'LazyPasswordField': typeof import("../components/PasswordField.vue")['default']
    'LazyProjectsActivityAddStaff': typeof import("../components/Projects/Activity/AddStaff.vue")['default']
    'LazyProjectsActivityFinance': typeof import("../components/Projects/Activity/Finance.vue")['default']
    'LazyProjectsActivityFinanceCreateFinance': typeof import("../components/Projects/Activity/Finance/CreateFinance.vue")['default']
    'LazyProjectsActivityFinanceDonations': typeof import("../components/Projects/Activity/Finance/Donations.vue")['default']
    'LazyProjectsActivityFinanceDonationsList': typeof import("../components/Projects/Activity/Finance/DonationsList.vue")['default']
    'LazyProjectsActivityFinanceExpenses': typeof import("../components/Projects/Activity/Finance/Expenses.vue")['default']
    'LazyProjectsActivityFinanceExpensesListOld': typeof import("../components/Projects/Activity/Finance/ExpensesList.old.vue")['default']
    'LazyProjectsActivityFinanceExpensesList': typeof import("../components/Projects/Activity/Finance/ExpensesList.vue")['default']
    'LazyProjectsActivityFinanceList': typeof import("../components/Projects/Activity/Finance/List.vue")['default']
    'LazyProjectsActivityFinanceUpdateFinance': typeof import("../components/Projects/Activity/Finance/UpdateFinance.vue")['default']
    'LazyProjectsActivitySetStaffData': typeof import("../components/Projects/Activity/SetStaffData.vue")['default']
    'LazyProjectsActivityStaff': typeof import("../components/Projects/Activity/Staff.vue")['default']
    'LazyProjectsActivityStaffCard': typeof import("../components/Projects/Activity/StaffCard.vue")['default']
    'LazyProjectsActivityStaffList': typeof import("../components/Projects/Activity/StaffList.vue")['default']
    'LazyProjectsActivityUpdateStaff': typeof import("../components/Projects/Activity/UpdateStaff.vue")['default']
    'LazyProjectsActivityViewData': typeof import("../components/Projects/Activity/ViewData.vue")['default']
    'LazyProjectsCreateData': typeof import("../components/Projects/CreateData.vue")['default']
    'LazyProjectsFinance': typeof import("../components/Projects/Finance.vue")['default']
    'LazyProjectsFinanceCreateProjectFinance': typeof import("../components/Projects/Finance/CreateProjectFinance.vue")['default']
    'LazyProjectsFinanceDonations': typeof import("../components/Projects/Finance/Donations.vue")['default']
    'LazyProjectsFinanceDonationsList': typeof import("../components/Projects/Finance/DonationsList.vue")['default']
    'LazyProjectsFinanceExpenses': typeof import("../components/Projects/Finance/Expenses.vue")['default']
    'LazyProjectsFinanceExpensesList': typeof import("../components/Projects/Finance/ExpensesList.vue")['default']
    'LazyProjectsFinanceUpdateProjectFinance': typeof import("../components/Projects/Finance/UpdateProjectFinance.vue")['default']
    'LazyProjectsList': typeof import("../components/Projects/List.vue")['default']
    'LazyProjectsProjectActivities': typeof import("../components/Projects/Project/Activities.vue")['default']
    'LazyProjectsProjectActivitySettings': typeof import("../components/Projects/Project/ActivitySettings.vue")['default']
    'LazyProjectsProjectAddStaff': typeof import("../components/Projects/Project/AddStaff.vue")['default']
    'LazyProjectsProjectCreateActivity': typeof import("../components/Projects/Project/CreateActivity.vue")['default']
    'LazyProjectsProjectSettings': typeof import("../components/Projects/Project/Settings.vue")['default']
    'LazyProjectsProjectStaffCard': typeof import("../components/Projects/Project/StaffCard.vue")['default']
    'LazyProjectsProjectStaffList': typeof import("../components/Projects/Project/StaffList.vue")['default']
    'LazyProjectsProjectUpdateActivity': typeof import("../components/Projects/Project/UpdateActivity.vue")['default']
    'LazyProjectsProjectUpdateStaff': typeof import("../components/Projects/Project/UpdateStaff.vue")['default']
    'LazyProjectsProjectViewData': typeof import("../components/Projects/Project/ViewData.vue")['default']
    'LazyProjectsSetStaffData': typeof import("../components/Projects/SetStaffData.vue")['default']
    'LazyProjectsStaff': typeof import("../components/Projects/Staff.vue")['default']
    'LazySaveCancelBtn': typeof import("../components/SaveCancelBtn.vue")['default']
    'LazySelectField': typeof import("../components/SelectField.vue")['default']
    'LazyTextEditor': typeof import("../components/TextEditor.vue")['default']
    'LazyTextField': typeof import("../components/TextField.vue")['default']
    'LazyTextareaField': typeof import("../components/TextareaField.vue")['default']
    'LazyWContactInfo': typeof import("../components/w/ContactInfo.vue")['default']
    'LazyWHtmlView': typeof import("../components/w/HtmlView.vue")['default']
    'LazyWHtmlViewDialog': typeof import("../components/w/HtmlViewDialog.vue")['default']
    'LazyWIdInfo': typeof import("../components/w/IdInfo.vue")['default']
    'LazyWMaritalStatusPicker': typeof import("../components/w/MaritalStatusPicker.vue")['default']
    'LazyWSelectAllowances': typeof import("../components/w/SelectAllowances.vue")['default']
    'LazyWSelectDeductions': typeof import("../components/w/SelectDeductions.vue")['default']
    'LazyWSelectEmployee': typeof import("../components/w/SelectEmployee.vue")['default']
    'LazyWSelectEmploymentStatus': typeof import("../components/w/SelectEmploymentStatus.vue")['default']
    'LazyWSelectMember': typeof import("../components/w/SelectMember.vue")['default']
    'LazyWSelectMembershipStatus': typeof import("../components/w/SelectMembershipStatus.vue")['default']
    'LazyWSelectOrgSection': typeof import("../components/w/SelectOrgSection.vue")['default']
    'LazyWSelectQualification': typeof import("../components/w/SelectQualification.vue")['default']
    'LazyWSexPicker': typeof import("../components/w/SexPicker.vue")['default']
    'LazyWUsd': typeof import("../components/w/Usd.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyTiptapEditorContent': typeof import("@tiptap/vue-3")['EditorContent']
    'LazyTiptapFloatingMenu': typeof import("@tiptap/vue-3")['FloatingMenu']
    'LazyTiptapBubbleMenu': typeof import("@tiptap/vue-3")['BubbleMenu']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const AllowancesOptionsCreate: typeof import("../components/AllowancesOptions/Create.vue")['default']
export const AllowancesOptionsList: typeof import("../components/AllowancesOptions/List.vue")['default']
export const AllowancesOptionsUpdate: typeof import("../components/AllowancesOptions/Update.vue")['default']
export const AvatarPicker: typeof import("../components/AvatarPicker.vue")['default']
export const BackendErrorWrapper: typeof import("../components/BackendErrorWrapper.vue")['default']
export const CreateEmployeeAuthentication: typeof import("../components/CreateEmployee/Authentication.vue")['default']
export const CreateEmployeeContactInfo: typeof import("../components/CreateEmployee/ContactInfo.vue")['default']
export const CreateEmployeeEmploymentInfo: typeof import("../components/CreateEmployee/EmploymentInfo.vue")['default']
export const CreateEmployeePersonalInfo: typeof import("../components/CreateEmployee/PersonalInfo.vue")['default']
export const CreateEmployeeSalary: typeof import("../components/CreateEmployee/Salary.vue")['default']
export const CreateEmployeeSalarySelectAllowances: typeof import("../components/CreateEmployee/SalarySelectAllowances.vue")['default']
export const CreateEmployeeSalarySelectDeductions: typeof import("../components/CreateEmployee/SalarySelectDeductions.vue")['default']
export const CreateEmployeeSelectRoles: typeof import("../components/CreateEmployee/SelectRoles.vue")['default']
export const CreateEmployeeSetPassword: typeof import("../components/CreateEmployee/SetPassword.vue")['default']
export const CreateMemberContactInfoOld: typeof import("../components/CreateMember/ContactInfo.old.vue")['default']
export const CreateMemberContactInfo: typeof import("../components/CreateMember/ContactInfo.vue")['default']
export const CreateMemberMembershipInfo: typeof import("../components/CreateMember/MembershipInfo.vue")['default']
export const CreateMemberPersonalInfoOld: typeof import("../components/CreateMember/PersonalInfo.old.vue")['default']
export const CreateMemberPersonalInfo: typeof import("../components/CreateMember/PersonalInfo.vue")['default']
export const CreateRoleSelectPermissions: typeof import("../components/CreateRole/SelectPermissions.vue")['default']
export const CreateUserAvatarPicker: typeof import("../components/CreateUser/AvatarPicker.vue")['default']
export const CreateUserSelectRoles: typeof import("../components/CreateUser/SelectRoles.vue")['default']
export const CreateUserDetails: typeof import("../components/CreateUser/UserDetails.vue")['default']
export const DatePicker: typeof import("../components/DatePicker.vue")['default']
export const DateView: typeof import("../components/DateView.vue")['default']
export const DeductionsOptionsCreate: typeof import("../components/DeductionsOptions/Create.vue")['default']
export const DeductionsOptionsList: typeof import("../components/DeductionsOptions/List.vue")['default']
export const DeductionsOptionsUpdate: typeof import("../components/DeductionsOptions/Update.vue")['default']
export const DefaultLayoutNavigationRail: typeof import("../components/DefaultLayout/NavigationRail.vue")['default']
export const DefaultLayoutUserCard: typeof import("../components/DefaultLayout/UserCard.vue")['default']
export const EmployeesEmployeeAuthInfo: typeof import("../components/Employees/EmployeeAuthInfo.vue")['default']
export const EmployeesEmployeeInfo: typeof import("../components/Employees/EmployeeInfo.vue")['default']
export const EmployeesEmployeeSalaryInfo: typeof import("../components/Employees/EmployeeSalaryInfo.vue")['default']
export const EmployeesEmployeeSettings: typeof import("../components/Employees/EmployeeSettings.vue")['default']
export const EmployeesList: typeof import("../components/Employees/List.vue")['default']
export const LoadingFromBackend: typeof import("../components/LoadingFromBackend.vue")['default']
export const MembersEmployeeSalaryInfo: typeof import("../components/Members/EmployeeSalaryInfo.vue")['default']
export const MembersList: typeof import("../components/Members/List.vue")['default']
export const MembersMemberInfo: typeof import("../components/Members/MemberInfo.vue")['default']
export const MembersMemberSettings: typeof import("../components/Members/MemberSettings.vue")['default']
export const MultiPhoneField: typeof import("../components/MultiPhoneField.vue")['default']
export const NumberField: typeof import("../components/NumberField.vue")['default']
export const PasswordField: typeof import("../components/PasswordField.vue")['default']
export const ProjectsActivityAddStaff: typeof import("../components/Projects/Activity/AddStaff.vue")['default']
export const ProjectsActivityFinance: typeof import("../components/Projects/Activity/Finance.vue")['default']
export const ProjectsActivityFinanceCreateFinance: typeof import("../components/Projects/Activity/Finance/CreateFinance.vue")['default']
export const ProjectsActivityFinanceDonations: typeof import("../components/Projects/Activity/Finance/Donations.vue")['default']
export const ProjectsActivityFinanceDonationsList: typeof import("../components/Projects/Activity/Finance/DonationsList.vue")['default']
export const ProjectsActivityFinanceExpenses: typeof import("../components/Projects/Activity/Finance/Expenses.vue")['default']
export const ProjectsActivityFinanceExpensesListOld: typeof import("../components/Projects/Activity/Finance/ExpensesList.old.vue")['default']
export const ProjectsActivityFinanceExpensesList: typeof import("../components/Projects/Activity/Finance/ExpensesList.vue")['default']
export const ProjectsActivityFinanceList: typeof import("../components/Projects/Activity/Finance/List.vue")['default']
export const ProjectsActivityFinanceUpdateFinance: typeof import("../components/Projects/Activity/Finance/UpdateFinance.vue")['default']
export const ProjectsActivitySetStaffData: typeof import("../components/Projects/Activity/SetStaffData.vue")['default']
export const ProjectsActivityStaff: typeof import("../components/Projects/Activity/Staff.vue")['default']
export const ProjectsActivityStaffCard: typeof import("../components/Projects/Activity/StaffCard.vue")['default']
export const ProjectsActivityStaffList: typeof import("../components/Projects/Activity/StaffList.vue")['default']
export const ProjectsActivityUpdateStaff: typeof import("../components/Projects/Activity/UpdateStaff.vue")['default']
export const ProjectsActivityViewData: typeof import("../components/Projects/Activity/ViewData.vue")['default']
export const ProjectsCreateData: typeof import("../components/Projects/CreateData.vue")['default']
export const ProjectsFinance: typeof import("../components/Projects/Finance.vue")['default']
export const ProjectsFinanceCreateProjectFinance: typeof import("../components/Projects/Finance/CreateProjectFinance.vue")['default']
export const ProjectsFinanceDonations: typeof import("../components/Projects/Finance/Donations.vue")['default']
export const ProjectsFinanceDonationsList: typeof import("../components/Projects/Finance/DonationsList.vue")['default']
export const ProjectsFinanceExpenses: typeof import("../components/Projects/Finance/Expenses.vue")['default']
export const ProjectsFinanceExpensesList: typeof import("../components/Projects/Finance/ExpensesList.vue")['default']
export const ProjectsFinanceUpdateProjectFinance: typeof import("../components/Projects/Finance/UpdateProjectFinance.vue")['default']
export const ProjectsList: typeof import("../components/Projects/List.vue")['default']
export const ProjectsProjectActivities: typeof import("../components/Projects/Project/Activities.vue")['default']
export const ProjectsProjectActivitySettings: typeof import("../components/Projects/Project/ActivitySettings.vue")['default']
export const ProjectsProjectAddStaff: typeof import("../components/Projects/Project/AddStaff.vue")['default']
export const ProjectsProjectCreateActivity: typeof import("../components/Projects/Project/CreateActivity.vue")['default']
export const ProjectsProjectSettings: typeof import("../components/Projects/Project/Settings.vue")['default']
export const ProjectsProjectStaffCard: typeof import("../components/Projects/Project/StaffCard.vue")['default']
export const ProjectsProjectStaffList: typeof import("../components/Projects/Project/StaffList.vue")['default']
export const ProjectsProjectUpdateActivity: typeof import("../components/Projects/Project/UpdateActivity.vue")['default']
export const ProjectsProjectUpdateStaff: typeof import("../components/Projects/Project/UpdateStaff.vue")['default']
export const ProjectsProjectViewData: typeof import("../components/Projects/Project/ViewData.vue")['default']
export const ProjectsSetStaffData: typeof import("../components/Projects/SetStaffData.vue")['default']
export const ProjectsStaff: typeof import("../components/Projects/Staff.vue")['default']
export const SaveCancelBtn: typeof import("../components/SaveCancelBtn.vue")['default']
export const SelectField: typeof import("../components/SelectField.vue")['default']
export const TextEditor: typeof import("../components/TextEditor.vue")['default']
export const TextField: typeof import("../components/TextField.vue")['default']
export const TextareaField: typeof import("../components/TextareaField.vue")['default']
export const WContactInfo: typeof import("../components/w/ContactInfo.vue")['default']
export const WHtmlView: typeof import("../components/w/HtmlView.vue")['default']
export const WHtmlViewDialog: typeof import("../components/w/HtmlViewDialog.vue")['default']
export const WIdInfo: typeof import("../components/w/IdInfo.vue")['default']
export const WMaritalStatusPicker: typeof import("../components/w/MaritalStatusPicker.vue")['default']
export const WSelectAllowances: typeof import("../components/w/SelectAllowances.vue")['default']
export const WSelectDeductions: typeof import("../components/w/SelectDeductions.vue")['default']
export const WSelectEmployee: typeof import("../components/w/SelectEmployee.vue")['default']
export const WSelectEmploymentStatus: typeof import("../components/w/SelectEmploymentStatus.vue")['default']
export const WSelectMember: typeof import("../components/w/SelectMember.vue")['default']
export const WSelectMembershipStatus: typeof import("../components/w/SelectMembershipStatus.vue")['default']
export const WSelectOrgSection: typeof import("../components/w/SelectOrgSection.vue")['default']
export const WSelectQualification: typeof import("../components/w/SelectQualification.vue")['default']
export const WSexPicker: typeof import("../components/w/SexPicker.vue")['default']
export const WUsd: typeof import("../components/w/Usd.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const TiptapEditorContent: typeof import("@tiptap/vue-3")['EditorContent']
export const TiptapFloatingMenu: typeof import("@tiptap/vue-3")['FloatingMenu']
export const TiptapBubbleMenu: typeof import("@tiptap/vue-3")['BubbleMenu']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyAllowancesOptionsCreate: typeof import("../components/AllowancesOptions/Create.vue")['default']
export const LazyAllowancesOptionsList: typeof import("../components/AllowancesOptions/List.vue")['default']
export const LazyAllowancesOptionsUpdate: typeof import("../components/AllowancesOptions/Update.vue")['default']
export const LazyAvatarPicker: typeof import("../components/AvatarPicker.vue")['default']
export const LazyBackendErrorWrapper: typeof import("../components/BackendErrorWrapper.vue")['default']
export const LazyCreateEmployeeAuthentication: typeof import("../components/CreateEmployee/Authentication.vue")['default']
export const LazyCreateEmployeeContactInfo: typeof import("../components/CreateEmployee/ContactInfo.vue")['default']
export const LazyCreateEmployeeEmploymentInfo: typeof import("../components/CreateEmployee/EmploymentInfo.vue")['default']
export const LazyCreateEmployeePersonalInfo: typeof import("../components/CreateEmployee/PersonalInfo.vue")['default']
export const LazyCreateEmployeeSalary: typeof import("../components/CreateEmployee/Salary.vue")['default']
export const LazyCreateEmployeeSalarySelectAllowances: typeof import("../components/CreateEmployee/SalarySelectAllowances.vue")['default']
export const LazyCreateEmployeeSalarySelectDeductions: typeof import("../components/CreateEmployee/SalarySelectDeductions.vue")['default']
export const LazyCreateEmployeeSelectRoles: typeof import("../components/CreateEmployee/SelectRoles.vue")['default']
export const LazyCreateEmployeeSetPassword: typeof import("../components/CreateEmployee/SetPassword.vue")['default']
export const LazyCreateMemberContactInfoOld: typeof import("../components/CreateMember/ContactInfo.old.vue")['default']
export const LazyCreateMemberContactInfo: typeof import("../components/CreateMember/ContactInfo.vue")['default']
export const LazyCreateMemberMembershipInfo: typeof import("../components/CreateMember/MembershipInfo.vue")['default']
export const LazyCreateMemberPersonalInfoOld: typeof import("../components/CreateMember/PersonalInfo.old.vue")['default']
export const LazyCreateMemberPersonalInfo: typeof import("../components/CreateMember/PersonalInfo.vue")['default']
export const LazyCreateRoleSelectPermissions: typeof import("../components/CreateRole/SelectPermissions.vue")['default']
export const LazyCreateUserAvatarPicker: typeof import("../components/CreateUser/AvatarPicker.vue")['default']
export const LazyCreateUserSelectRoles: typeof import("../components/CreateUser/SelectRoles.vue")['default']
export const LazyCreateUserDetails: typeof import("../components/CreateUser/UserDetails.vue")['default']
export const LazyDatePicker: typeof import("../components/DatePicker.vue")['default']
export const LazyDateView: typeof import("../components/DateView.vue")['default']
export const LazyDeductionsOptionsCreate: typeof import("../components/DeductionsOptions/Create.vue")['default']
export const LazyDeductionsOptionsList: typeof import("../components/DeductionsOptions/List.vue")['default']
export const LazyDeductionsOptionsUpdate: typeof import("../components/DeductionsOptions/Update.vue")['default']
export const LazyDefaultLayoutNavigationRail: typeof import("../components/DefaultLayout/NavigationRail.vue")['default']
export const LazyDefaultLayoutUserCard: typeof import("../components/DefaultLayout/UserCard.vue")['default']
export const LazyEmployeesEmployeeAuthInfo: typeof import("../components/Employees/EmployeeAuthInfo.vue")['default']
export const LazyEmployeesEmployeeInfo: typeof import("../components/Employees/EmployeeInfo.vue")['default']
export const LazyEmployeesEmployeeSalaryInfo: typeof import("../components/Employees/EmployeeSalaryInfo.vue")['default']
export const LazyEmployeesEmployeeSettings: typeof import("../components/Employees/EmployeeSettings.vue")['default']
export const LazyEmployeesList: typeof import("../components/Employees/List.vue")['default']
export const LazyLoadingFromBackend: typeof import("../components/LoadingFromBackend.vue")['default']
export const LazyMembersEmployeeSalaryInfo: typeof import("../components/Members/EmployeeSalaryInfo.vue")['default']
export const LazyMembersList: typeof import("../components/Members/List.vue")['default']
export const LazyMembersMemberInfo: typeof import("../components/Members/MemberInfo.vue")['default']
export const LazyMembersMemberSettings: typeof import("../components/Members/MemberSettings.vue")['default']
export const LazyMultiPhoneField: typeof import("../components/MultiPhoneField.vue")['default']
export const LazyNumberField: typeof import("../components/NumberField.vue")['default']
export const LazyPasswordField: typeof import("../components/PasswordField.vue")['default']
export const LazyProjectsActivityAddStaff: typeof import("../components/Projects/Activity/AddStaff.vue")['default']
export const LazyProjectsActivityFinance: typeof import("../components/Projects/Activity/Finance.vue")['default']
export const LazyProjectsActivityFinanceCreateFinance: typeof import("../components/Projects/Activity/Finance/CreateFinance.vue")['default']
export const LazyProjectsActivityFinanceDonations: typeof import("../components/Projects/Activity/Finance/Donations.vue")['default']
export const LazyProjectsActivityFinanceDonationsList: typeof import("../components/Projects/Activity/Finance/DonationsList.vue")['default']
export const LazyProjectsActivityFinanceExpenses: typeof import("../components/Projects/Activity/Finance/Expenses.vue")['default']
export const LazyProjectsActivityFinanceExpensesListOld: typeof import("../components/Projects/Activity/Finance/ExpensesList.old.vue")['default']
export const LazyProjectsActivityFinanceExpensesList: typeof import("../components/Projects/Activity/Finance/ExpensesList.vue")['default']
export const LazyProjectsActivityFinanceList: typeof import("../components/Projects/Activity/Finance/List.vue")['default']
export const LazyProjectsActivityFinanceUpdateFinance: typeof import("../components/Projects/Activity/Finance/UpdateFinance.vue")['default']
export const LazyProjectsActivitySetStaffData: typeof import("../components/Projects/Activity/SetStaffData.vue")['default']
export const LazyProjectsActivityStaff: typeof import("../components/Projects/Activity/Staff.vue")['default']
export const LazyProjectsActivityStaffCard: typeof import("../components/Projects/Activity/StaffCard.vue")['default']
export const LazyProjectsActivityStaffList: typeof import("../components/Projects/Activity/StaffList.vue")['default']
export const LazyProjectsActivityUpdateStaff: typeof import("../components/Projects/Activity/UpdateStaff.vue")['default']
export const LazyProjectsActivityViewData: typeof import("../components/Projects/Activity/ViewData.vue")['default']
export const LazyProjectsCreateData: typeof import("../components/Projects/CreateData.vue")['default']
export const LazyProjectsFinance: typeof import("../components/Projects/Finance.vue")['default']
export const LazyProjectsFinanceCreateProjectFinance: typeof import("../components/Projects/Finance/CreateProjectFinance.vue")['default']
export const LazyProjectsFinanceDonations: typeof import("../components/Projects/Finance/Donations.vue")['default']
export const LazyProjectsFinanceDonationsList: typeof import("../components/Projects/Finance/DonationsList.vue")['default']
export const LazyProjectsFinanceExpenses: typeof import("../components/Projects/Finance/Expenses.vue")['default']
export const LazyProjectsFinanceExpensesList: typeof import("../components/Projects/Finance/ExpensesList.vue")['default']
export const LazyProjectsFinanceUpdateProjectFinance: typeof import("../components/Projects/Finance/UpdateProjectFinance.vue")['default']
export const LazyProjectsList: typeof import("../components/Projects/List.vue")['default']
export const LazyProjectsProjectActivities: typeof import("../components/Projects/Project/Activities.vue")['default']
export const LazyProjectsProjectActivitySettings: typeof import("../components/Projects/Project/ActivitySettings.vue")['default']
export const LazyProjectsProjectAddStaff: typeof import("../components/Projects/Project/AddStaff.vue")['default']
export const LazyProjectsProjectCreateActivity: typeof import("../components/Projects/Project/CreateActivity.vue")['default']
export const LazyProjectsProjectSettings: typeof import("../components/Projects/Project/Settings.vue")['default']
export const LazyProjectsProjectStaffCard: typeof import("../components/Projects/Project/StaffCard.vue")['default']
export const LazyProjectsProjectStaffList: typeof import("../components/Projects/Project/StaffList.vue")['default']
export const LazyProjectsProjectUpdateActivity: typeof import("../components/Projects/Project/UpdateActivity.vue")['default']
export const LazyProjectsProjectUpdateStaff: typeof import("../components/Projects/Project/UpdateStaff.vue")['default']
export const LazyProjectsProjectViewData: typeof import("../components/Projects/Project/ViewData.vue")['default']
export const LazyProjectsSetStaffData: typeof import("../components/Projects/SetStaffData.vue")['default']
export const LazyProjectsStaff: typeof import("../components/Projects/Staff.vue")['default']
export const LazySaveCancelBtn: typeof import("../components/SaveCancelBtn.vue")['default']
export const LazySelectField: typeof import("../components/SelectField.vue")['default']
export const LazyTextEditor: typeof import("../components/TextEditor.vue")['default']
export const LazyTextField: typeof import("../components/TextField.vue")['default']
export const LazyTextareaField: typeof import("../components/TextareaField.vue")['default']
export const LazyWContactInfo: typeof import("../components/w/ContactInfo.vue")['default']
export const LazyWHtmlView: typeof import("../components/w/HtmlView.vue")['default']
export const LazyWHtmlViewDialog: typeof import("../components/w/HtmlViewDialog.vue")['default']
export const LazyWIdInfo: typeof import("../components/w/IdInfo.vue")['default']
export const LazyWMaritalStatusPicker: typeof import("../components/w/MaritalStatusPicker.vue")['default']
export const LazyWSelectAllowances: typeof import("../components/w/SelectAllowances.vue")['default']
export const LazyWSelectDeductions: typeof import("../components/w/SelectDeductions.vue")['default']
export const LazyWSelectEmployee: typeof import("../components/w/SelectEmployee.vue")['default']
export const LazyWSelectEmploymentStatus: typeof import("../components/w/SelectEmploymentStatus.vue")['default']
export const LazyWSelectMember: typeof import("../components/w/SelectMember.vue")['default']
export const LazyWSelectMembershipStatus: typeof import("../components/w/SelectMembershipStatus.vue")['default']
export const LazyWSelectOrgSection: typeof import("../components/w/SelectOrgSection.vue")['default']
export const LazyWSelectQualification: typeof import("../components/w/SelectQualification.vue")['default']
export const LazyWSexPicker: typeof import("../components/w/SexPicker.vue")['default']
export const LazyWUsd: typeof import("../components/w/Usd.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyTiptapEditorContent: typeof import("@tiptap/vue-3")['EditorContent']
export const LazyTiptapFloatingMenu: typeof import("@tiptap/vue-3")['FloatingMenu']
export const LazyTiptapBubbleMenu: typeof import("@tiptap/vue-3")['BubbleMenu']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
